version: '3.8'

services:
  flask:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - DATABASE_URI=${DATABASE_URI}
    depends_on:
      - db
    networks:
      - app-network
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        max_attempts: 3

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - app-network
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  app-network:
    driver: overlay

volumes:
  postgres_data: