version: '3.8'

services:
  flask:
    image: flashnews-backend_sqlite:latest
    ports:
      - "${FLASK_PORT}:5000"
    env_file:
      - .env
    volumes:
      - sqlite_data:/app/instance
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    networks:
      - app-network

networks:
  app-network:
    driver: overlay

volumes:
  sqlite_data:
    driver: local