version: '3.8'

services:
  flask:
    build: ./backend
    ports:
      - "${FLASK_PORT}:5000"
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - DATABASE_URI=${DATABASE_URI}
    depends_on:
      - db
    networks:
      - app-network
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        max_attempts: 3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${FLASK_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:13
    volumes:
      - sqlite_data:/var/lib/sqlite/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flashnews
    networks:
      - app-network
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  app-network:
    driver: overlay

volumes:
  sqlite_data:
