name: Test Backend

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: ./backend
        run: pip install -r requirements.txt

      - name: Run tests
        working-directory: ./backend
        run: python -m pytest
